version: '3.3'

services:
  my-backend:
    platform: linux/x86_64
    image: asia.gcr.io/evocative-tube-352516/team:2.3.7
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
